version: '3'

name: devise_gauth

services:
  gem:
    build: .
    environment:
      - EARTHLY_DEVISE_VERSION=${EARTHLY_DEVISE_VERSION}
      - EARTHLY_RAILS_VERSION=${EARTHLY_RAILS_VERSION}
      - EARTHLY_RUBY_VERSION=${EARTHLY_RUBY_VERSION}
    image: pharmony/devise_gauth:latest
    volumes:
      - ./tmp/:/gem/test/rails_app/tmp/
