on:
   push:
     branches:
       - master
   pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          #
          # Rails 4.x series
          #
          # Rails 4.2 compatible versions
          - ruby: 2.5
            rails: 4.2.11.3
            devise: 4.8.1

          #
          # Rails 5.x series
          #
          # Rails 5.0 compatible versions
          - ruby: 2.5 # We should use 2.4 but Nokogiri requires 2.5
            rails: 5.0.7.2
            devise: 4.8.1
          # Rails 5.1 compatible versions
          - ruby: 2.5
            rails: 5.1.7
            devise: 4.8.1
          # Rails 5.2 compatible versions
          - ruby: 2.5
            rails: 5.2.8.1
            devise: 4.8.1
          # Rails 5.2 compatible versions
          - ruby: 2.6
            rails: 5.2.8.1
            devise: 4.8.1

          #
          # Rails 6.x series
          #
          # Rails 6.0 compatible versions
          - ruby: 2.6
            rails: 6.0.6.1
            devise: 4.9.3
          # Rails 6.0 compatible versions
          - ruby: 2.7
            rails: 6.0.6.1
            devise: 4.9.3
          # Rails 6.1 compatible versions
          - ruby: 3.0
            rails: 6.1.7.10
            devise: 4.9.4
          # Rails 6.1 compatible versions
          - ruby: 3.1
            rails: 6.1.7.10
            devise: 4.9.4

          #
          # Rails 7.x series
          #
          - ruby: 3.1
            rails: 7.0.8.7
            devise: 4.9.4
          - ruby: 3.2
            rails: 7.0.8.7
            devise: 4.9.4
          # This can't work since the `test/rails_app/` needs to be upgraded
          # See https://github.com/Pharmony/devise_gauth/issues/12
          # - ruby: 3.2
          #   rails: 7.1.5.1
          #   devise: 4.9.4
          # - ruby: 3.3
          #   rails: 7.2.2.1
          #   devise: 4.9.4
    runs-on: ubuntu-latest
    name: RSpec suite (Ruby ${{ matrix.ruby }}/Rails ${{ matrix.rails }}/Devise ${{ matrix.devise }})
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      EARTHLY_DEVISE_VERSION: ${{ matrix.devise }}
      EARTHLY_RAILS_VERSION: ${{ matrix.rails }}
      EARTHLY_RUBY_VERSION: ${{ matrix.ruby }}
      FORCE_COLOR: 1
    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.0
    - uses: actions/checkout@v4
    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
    - name: Earthly version
      run: earthly --version
    - name: Run build
      run: |
        earthly --ci --allow-privileged --output +test --EARTHLY_RUBY_VERSION=$EARTHLY_RUBY_VERSION --EARTHLY_RAILS_VERSION=$EARTHLY_RAILS_VERSION --EARTHLY_DEVISE_VERSION=$EARTHLY_DEVISE_VERSION
